// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACWoNkggl9qB25MaR7oMOssmGImCKIxQQ',
    appId: '1:474086444514:web:d0d61554410dc216c63dbb',
    messagingSenderId: '474086444514',
    projectId: 'pathshala-684b7',
    authDomain: 'pathshala-684b7.firebaseapp.com',
    storageBucket: 'pathshala-684b7.appspot.com',
    measurementId: 'G-5XB949G30P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_nMuonjWvjFtwo7m7ju1LuAxEGfyQL8E',
    appId: '1:474086444514:android:a296994cf57aa56fc63dbb',
    messagingSenderId: '474086444514',
    projectId: 'pathshala-684b7',
    storageBucket: 'pathshala-684b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQyZTR6fslo6EiDDBiTPPeOjzW-4r0-5c',
    appId: '1:474086444514:ios:81f61120ba4aa00fc63dbb',
    messagingSenderId: '474086444514',
    projectId: 'pathshala-684b7',
    storageBucket: 'pathshala-684b7.appspot.com',
    iosClientId: '474086444514-cp1ibh9tnsec7afkj03gn9lk36kb9fsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pathsala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQyZTR6fslo6EiDDBiTPPeOjzW-4r0-5c',
    appId: '1:474086444514:ios:81f61120ba4aa00fc63dbb',
    messagingSenderId: '474086444514',
    projectId: 'pathshala-684b7',
    storageBucket: 'pathshala-684b7.appspot.com',
    iosClientId: '474086444514-cp1ibh9tnsec7afkj03gn9lk36kb9fsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pathsala',
  );
}
